M48
; DRILL file {KiCad 8.0.1} date 2024-03-26T10:43:19-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-26T10:43:19-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X6.0594Y-2.9228
X6.7681Y-2.9228
T2
X5.1Y-2.4
X5.1Y-4.0
X5.7Y-2.4
X5.7Y-4.0
T3
X3.3506Y-3.7874
X4.4128Y-3.7874
M30
