M48
; DRILL file {KiCad 7.0.10} date Thu Feb 15 22:29:53 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-15T22:29:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X5.9819Y-3.0478
X6.6906Y-3.0478
T2
X5.1Y-2.4
X5.1Y-4.0
X5.7Y-2.4
X5.7Y-4.0
T3
X3.4Y-3.7191
X4.6Y-3.7039
X6.2075Y-3.9
X6.3925Y-3.9
M30
